#-----------------------------------------------------------
#   Copyright 2006-2012 (c) Alkaline Games LLC
# 
#   This Source Code Form is subject to the terms of the Mozilla Public
#   License, v. 2.0. If a copy of the MPL was not distributed with this
#   file, You can obtain one at http://mozilla.org/MPL/2.0/.
#-----------------------------------------------------------
#       file:   makefile
#    project:   Beach Expression
#   platform:   independent
#     format:   GNU Make
#    authors:   Christopher Augustus
#-----------------------------------------------------------
#   Build the expression tests.
#-----------------------------------------------------------

PARENT_RELATIVE_PATH := ..

include $(PARENT_RELATIVE_PATH)/make_include_parent

#---------------------------------------
#   targets
#---------------------------------------

MAKES :=\
 makefile_console\
 makefile_test

include $(BUILD_DIR)/make_include_target_makes

#---------------------------------------
# (end of file)	 			
