#!/bin/bash
# debug the shell and execute initial run commands
# NOTE: this variation is no longer used but kept to preserve the code
#
HAS_READLINK=`which readlink`
if [[ -z $HAS_READLINK ]]
then
    THIS_SYMLINK_PATH='.'
    SUBDEBUG=../../../../any/debug/subdebug
else
    THIS_SYMLINK=`readlink $0`
    THIS_SYMLINK_PATH=${THIS_SYMLINK%/*}
    SUBDEBUG=$THIS_SYMLINK_PATH/../../subdebug
fi
source $SUBDEBUG gdb shell shell coast_shell --command=$THIS_SYMLINK_PATH/gdb_cmds_run_shell
#
# $Log: subdebug_via_symlink_caller_example,v $
# Revision 1.3  2008/09/10 06:34:15  cat
# renamed sandbar to coast
#
# Revision 1.2  2007/05/06 09:09:51  cat
# copied to preserve this code
#
# Revision 1.1  2007/02/23 08:12:12  cat
# creation
#
