#-----------------------------------------------------------
#   Copyright 2002-2017 (c) Alkaline Games LLC
# 
#   This Source Code Form is subject to the terms of the Mozilla Public
#   License, v. 2.0. If a copy of the MPL was not distributed with this
#   file, You can obtain one at http://mozilla.org/MPL/2.0/.
#-----------------------------------------------------------
#       file:   makefile
#    project:   Beach Atoms
#   platform:   independent
#     format:   GNU Make
#    authors:   Christopher Augustus
#-----------------------------------------------------------
#   Build the atoms libraries.
#-----------------------------------------------------------

#---------------------------------------
#    variables and rules
#---------------------------------------

PARENT_RELATIVE_PATH := ..

include $(PARENT_RELATIVE_PATH)/make_include_parent
include $(BUILD_DIR)/make_include_settings

#---------------------------------------
#   targets
#---------------------------------------

MAKES :=\
 makefile_atoms\
 makefile_atoms_allocation

include $(BUILD_DIR)/make_include_target_makes
	
#---------------------------------------
# (end of file)	 			
