#!/bin/bash
#-----------------------------------------------------------
#
#  Copyright 2002-2012 (c) World Fusion (r)
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#-----------------------------------------------------------
# determine platform and set variables
#
UNAMEM=`uname -m`
UNAMES=`uname -s`
OSARCH=$UNAMEM
if [ "${UNAMES}" == "Darwin" ]
then
    OS=macosx
    CMD_MAKE=make
elif [ "${UNAMES}" == "FreeBSD" ]
then
    OS=freebsd
    CMD_MAKE=gmake
elif [ "${UNAMES}" == "Linux" ]
then
    OS=gnu_linux
    CMD_MAKE=make
elif [ "${UNAMES/_*/}" == "MINGW32" ]
then
    OS=mingw
    CMD_MAKE=make
    EXE_EXT=.exe
else
    echo "platform ${UNAMES} is not supported"
    exit 1
fi
PLATFORM="${OS}_${OSARCH}"
echo "PLATFORM==$PLATFORM"
# (end)
