#!/bin/sh
# delete all symbolic links
#
SUBSCRIPT_GET_PLATFORM=shsub_get_platform
TOPDIR=..
while [[ ! -f $TOPDIR/$SUBSCRIPT_GET_PLATFORM ]]
do
    TOPDIR=$TOPDIR/..
    if [[ ! -d $TOPDIR ]]
    then
        echo "!!! must be in a platform subdirectory below "$SUBSCRIPT_GET_PLATFORM
        exit 1
    fi
done
rm `find . -type l`
#
# $Log: shdeletesymlinks,v $
# Revision 1.3  2008/06/17 18:48:00  cat
# find command corrected
#
# Revision 1.2  2007/12/17 10:04:36  cat
# only allow in platform subdirectory
#
# Revision 1.1  2007/12/16 16:30:09  cat
# copy of rmsymlinks
#
