#define VERSION_BEACH_MAJOR 3
#define VERSION_BEACH_MINOR 0
#define VERSION_BEACH_BUILD 0
#define VERSION_NUMBER(MAJOR,MINOR,BUILD) # MAJOR "." # MINOR "." # BUILD
#define VERSION_STRING(MAJOR,MINOR,BUILD) VERSION_NUMBER(MAJOR,MINOR,BUILD)
#define VERSION_BEACH VERSION_STRING(VERSION_BEACH_MAJOR,VERSION_BEACH_MINOR,VERSION_BEACH_BUILD)
